/**
 * Wire fixtures mirroring the backend `/form-authority` and object projection
 * documents recorded from a real managed Active built on
 * `config/strategy.example.json`. Field names, enums and reference records come
 * from the server projection, never a hand-typed frontend invention.
 */

export const formAuthorityPayload = {
  active: {
    revisionId: "11111111-1111-4111-8111-111111111111",
    version: 1,
    revisionSequence: 1,
    status: "active",
    schemaVersion: 1,
    digest: "0".repeat(64),
    createdAt: "2026-01-01T00:00:00+00:00",
    updatedAt: "2026-01-01T00:00:00+00:00",
    validatedAt: null,
    activatedAt: null,
    validationErrors: [],
  },
  sideEffects: "none",
  families: [
    {
      family: "recognitionRules", kind: "recognition_rule", label: "RecognitionRule",
      fields: ["id", "name", "description", "condition", "outputRecognitionType", "enabled", "priority", "score", "stopOnMatch"],
      defaults: { name: "", description: "", condition: { operator: "always", children: [] }, outputRecognitionType: "", enabled: true, priority: 0, score: 1, stopOnMatch: false },
      supportsEnabled: true, actions: { create: true, edit: true, copy: true, toggle: true, remove: true, blocker: null },
    },
    {
      family: "typeBindings", kind: "recognition_type_policy", label: "RecognitionTypePolicy",
      fields: ["id", "name", "recognitionType", "metadataPolicy", "namingPolicy", "classificationPolicy", "organizePolicy", "enabled", "priority"],
      defaults: { name: "", recognitionType: "", metadataPolicy: "", namingPolicy: "", classificationPolicy: "", organizePolicy: "", enabled: true, priority: 0 },
      supportsEnabled: true, actions: { create: true, edit: true, copy: true, toggle: true, remove: true, blocker: null },
    },
    {
      family: "recognitionTypes",
      kind: "recognition_type",
      label: "RecognitionType",
      fields: ["id", "name", "description", "enabled"],
      defaults: { description: "", enabled: true, name: "" },
      supportsEnabled: true,
      actions: {
        create: true,
        edit: true,
        copy: true,
        toggle: true,
        remove: true,
        blocker: null,
      },
    },
    {
      family: "metadataPolicies",
      kind: "metadata_policy",
      label: "MetadataPolicy",
      fields: [
        "id",
        "name",
        "providerId",
        "mediaType",
        "mediaQueryType",
        "language",
        "region",
        "automaticThreshold",
        "confirmationThreshold",
        "minimumScoreGap",
        "timeout",
        "retryCount",
        "maxCandidates",
        "maxSearchPages",
        "maxProviderRequests",
        "maxCandidateEnrichments",
        "enabled",
      ],
      defaults: {
        automaticThreshold: 90,
        confirmationThreshold: 70,
        enabled: true,
        language: "zh-CN",
        maxCandidateEnrichments: 1,
        maxCandidates: 5,
        maxProviderRequests: 4,
        maxSearchPages: 1,
        minimumScoreGap: 5,
        name: "",
        providerId: "tmdb",
        region: "CN",
        retryCount: 1,
        timeout: 10,
      },
      supportsEnabled: true,
      actions: {
        create: true,
        edit: true,
        copy: true,
        toggle: true,
        remove: true,
        blocker: null,
      },
    },
    {
      family: "namingPolicies",
      kind: "naming_policy",
      label: "NamingPolicy",
      fields: [
        "id",
        "name",
        "description",
        "enabled",
        "mediaTypeMode",
        "directoryTemplate",
        "filenameTemplate",
        "seriesDirectoryTemplate",
        "seasonDirectoryTemplate",
        "episodeFilenameTemplate",
        "multiEpisodeFileTemplate",
        "missingVariableStrategy",
        "maxComponentLength",
      ],
      defaults: {
        description: "",
        directoryTemplate: "{title} ({year})",
        enabled: true,
        episodeFilenameTemplate:
          "{title} - S{season:02}E{episode:02} - {episode_title}.{ext}",
        filenameTemplate: "{title} ({year}).{ext}",
        maxComponentLength: 200,
        mediaTypeMode: "auto",
        missingVariableStrategy: "omit_token",
        multiEpisodeFileTemplate: "{title} - S{season:02}{episodes}.{ext}",
        name: "",
        seasonDirectoryTemplate: "Season {season:02}",
        seriesDirectoryTemplate: "{title} ({year})",
      },
      supportsEnabled: true,
      actions: {
        create: true,
        edit: true,
        copy: true,
        toggle: true,
        remove: true,
        blocker: null,
      },
    },
    {
      family: "classificationPolicies",
      kind: "classification_policy",
      label: "ClassificationPolicy",
      fields: ["id", "name", "description", "enabled", "priority", "rules"],
      defaults: {
        description: "",
        enabled: true,
        name: "",
        priority: 0,
        rules: [],
      },
      supportsEnabled: true,
      actions: {
        create: true,
        edit: true,
        copy: true,
        toggle: true,
        remove: true,
        blocker: null,
      },
    },
    {
      family: "organizePolicies",
      kind: "organize_policy",
      label: "OrganizePolicy",
      fields: [
        "id",
        "operation",
        "conflictStrategy",
        "overwrite",
        "duplicateDetection",
        "rollback",
        "sourceDirectoryCleanup",
        "attachments",
      ],
      defaults: {
        attachments: {
          enabled: true,
          nfo: true,
          otherSameStem: false,
          subtitles: true,
        },
        conflictStrategy: "manual",
        duplicateDetection: { mode: "none" },
        operation: "move",
        overwrite: false,
        rollback: { enabled: true },
        sourceDirectoryCleanup: { mode: "none" },
      },
      supportsEnabled: false,
      actions: {
        create: true,
        edit: true,
        copy: true,
        toggle: false,
        remove: true,
        blocker: null,
      },
    },
  ],
  mediaLibraries: [
    { id: "movies", name: "Movies", enabled: true, storageId: "media-target" },
    { id: "tv", name: "TV Shows", enabled: true, storageId: "media-target" },
  ],
  metadataProviders: [
    {
      providerId: "tmdb",
      secretReadiness: [
        { field: "TMDB_ACCESS_TOKEN", state: "SET" },
        { field: "TMDB_TOKEN", state: "UNSET" },
      ],
    },
  ],
  catalogs: {
    recognitionTypes: [{ id: "A", name: "A", enabled: true }, { id: "C", name: "C", enabled: true }],
    metadataPolicies: [{ id: "meta-a", name: "Metadata A", enabled: true }],
    namingPolicies: [{ id: "name-a", name: "Naming A", enabled: true }],
    classificationPolicies: [{ id: "class-a", name: "Classification A", enabled: true }],
    organizePolicies: [{ id: "org-a", name: "Organize A", enabled: true }],
  },
  enums: {
    mediaTypes: ["movie", "tv"],
    mediaQueryTypes: ["auto", "movie", "tv"],
    namingMediaTypeModes: ["auto", "movie", "tv"],
    missingVariableStrategies: ["error", "empty", "omit_token"],
    namingTemplates: [
      "directoryTemplate",
      "filenameTemplate",
      "seriesDirectoryTemplate",
      "seasonDirectoryTemplate",
      "episodeFilenameTemplate",
      "multiEpisodeFileTemplate",
    ],
    namingVariables: [
      "audio",
      "audio_channels",
      "audio_codec",
      "episode",
      "episode_range",
      "episode_title",
      "episodes",
      "ext",
      "hdr",
      "original_title",
      "provider",
      "provider_id",
      "release_group",
      "resolution",
      "season",
      "source",
      "title",
      "version",
      "video_codec",
      "year",
    ],
    numericNamingVariables: ["year", "season", "episode"],
    classificationConditions: [
      "mediaType",
      "genres",
      "countries",
      "languages",
      "yearMin",
      "yearMax",
      "canonicalYear",
      "keywords",
    ],
    organizeOperations: ["move", "copy", "hard_link", "soft_link"],
    conflictStrategies: ["manual", "skip", "rename", "overwrite"],
    cleanupModes: ["none", "empty_directories", "full_if_empty", "full"],
    hashModes: ["none", "size_only", "sample_hash", "full_hash"],
    conditionFields: ["filename", "path", "title_candidate", "year", "season", "episode", "resolution_tag", "source_tag"],
    conditionOperators: ["equals", "not_equals", "contains", "not_contains", "starts_with", "ends_with", "in", "not_in", "regex", "greater_than", "greater_than_or_equal", "less_than", "less_than_or_equal", "between", "contains_any", "contains_all"],
    logicalOperators: ["and", "or", "not", "always"],
  },
  limits: {
    objectId: 64,
    name: 120,
    description: 1000,
    maxComponentLength: { minimum: 8, maximum: 255 },
    classificationRules: { minimum: 1, maximum: 128 },
  },
};

export const editProjectionPayload = {
  family: "recognitionTypes",
  object: {
    id: "C",
    name: "Special",
    description: "Special handling",
    enabled: true,
  },
  references: {
    total: 2,
    items: [
      {
        section: "recognitionRules",
        id: "special",
        field: "outputRecognitionType",
        label: "Special rule",
      },
      {
        section: "recognitionTypePolicies",
        id: "type-C",
        field: "recognitionType",
        label: "type-C",
      },
    ],
    truncated: false,
    removalBlocked: true,
  },
  active: formAuthorityPayload.active,
  sideEffects: "none",
};

export const copyProjectionPayload = {
  family: "recognitionTypes",
  object: {
    id: "C-copy",
    name: "Special copy",
    description: "Special handling",
    enabled: false,
  },
  source: { id: "C", name: "Special" },
  active: formAuthorityPayload.active,
  sideEffects: "none",
  nextAction:
    "review the copied RecognitionType fields and save to publish it as Active",
};

export const saveSuccessPayload = {
  family: "recognitionTypes",
  action: "create",
  object: { id: "movie", name: "Movie", description: "", enabled: true },
  removed: null,
  active: { ...formAuthorityPayload.active, revisionSequence: 2, version: 2 },
  configuration: {
    authority: "MANAGED",
    revisionId: "22222222-2222-4222-8222-222222222222",
    version: 2,
    digest: "1".repeat(64),
  },
  sideEffects: "configuration_only",
  nextAction:
    "refresh the Active rules inventory; the published successor is the configuration runtime consumes",
};
